language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libev-dev libpcre3-dev
  - cd ..
  - git clone https://github.com/pandax381/rlogd.git rlogd
  - cd rlogd
  - ./autogen.sh
  - ./configure
  - make
  
env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1 TESTS="--show-all"

before_script:
  - phpize && ./configure --with-librlog-dir=../rlogd/ && make

script:
  - make test | tee test-output.txt && grep 'TEST SUMMARY$' test-output.txt > /dev/null ; test $? '!=' 0
