sudo: false
language: c

os:
  - linux
  - osx

compiler:
  - clang
  - gcc
  
matrix:
  exclude:
    - os: osx
      compiler: gcc

before_script:
  - phpize && ./configure --with-rlogd-src-dir=../rlogd/ && make

script:
  - make test | tee test-output.txt && grep 'TEST SUMMARY$' test-output.txt > /dev/null ; test $? '!=' 0
