sudo: false
language: c
os: osx

env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1 TESTS="--show-all" ax_cv_have_EV=yes ax_cv_have_PCRE=yes

before_install:
  - ls -la /Users/travis/
  - mkdir -p /Users/travis/.phpenv/versions/
  - phpenv global 7.0

before_script:
  - phpize && ./configure --with-rlogd-src-dir=../rlogd/ && make

script:
  - make test | tee test-output.txt && grep 'TEST SUMMARY$' test-output.txt > /dev/null ; test $? '!=' 0
